// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Qbou1j9blfYkABcQeSyNDpvMYKJQz90',
    appId: '1:873113452698:web:56b21b9b8d483ce989df23',
    messagingSenderId: '873113452698',
    projectId: 'get-gains-38ceb',
    authDomain: 'get-gains-38ceb.firebaseapp.com',
    storageBucket: 'get-gains-38ceb.firebasestorage.app',
    measurementId: 'G-7DMP2X54PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjyKPO7g-bpzDfd9Mud6WgzW79TLOjtmA',
    appId: '1:873113452698:android:fbb2adfcc958747389df23',
    messagingSenderId: '873113452698',
    projectId: 'get-gains-38ceb',
    storageBucket: 'get-gains-38ceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltRE12wlya8d0-DHQY013G4r7qQHSQf0',
    appId: '1:873113452698:ios:fa74527bece46a4a89df23',
    messagingSenderId: '873113452698',
    projectId: 'get-gains-38ceb',
    storageBucket: 'get-gains-38ceb.firebasestorage.app',
    iosBundleId: 'com.example.getGainsOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltRE12wlya8d0-DHQY013G4r7qQHSQf0',
    appId: '1:873113452698:ios:fa74527bece46a4a89df23',
    messagingSenderId: '873113452698',
    projectId: 'get-gains-38ceb',
    storageBucket: 'get-gains-38ceb.firebasestorage.app',
    iosBundleId: 'com.example.getGainsOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Qbou1j9blfYkABcQeSyNDpvMYKJQz90',
    appId: '1:873113452698:web:b10061baba6dbfa589df23',
    messagingSenderId: '873113452698',
    projectId: 'get-gains-38ceb',
    authDomain: 'get-gains-38ceb.firebaseapp.com',
    storageBucket: 'get-gains-38ceb.firebasestorage.app',
    measurementId: 'G-VT1BX6TB99',
  );
}
